name: Deploy Teste Para Produção

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Teste Para Produção
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Installing Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: build
          clean: true
